---
#20260514 11327110 ceUeval10
- hosts: dev
  tasks:
  - name: Ensure group "sharegrp" exists
    ansible.builtin.group:
      name: sharegrp
      state: present
  - name: Remove user 'james'
    ansible.builtin.user:
      name: james
      state: absent
      remove: yes
  - name: Add user 'james'
    ansible.builtin.user:
      name: james
      groups: sharegrp
      password: "{{ '123qwe' | password_hash('sha512') }}"
      password_expire_max: 10
